hostname OSPFv2
log file /var/log/quagga/ospfd.log
log stdout
password Quagga
enable password Quagga

router ospf
 router-id 10.0.1.18
 capability opaque
 log-adjacency-changes detail
 network 10.0.1.0/29 area 0
 network 10.0.1.8/29 area 0
 network 10.0.1.16/29 area 0
 network 172.16.123.128/28 area 0
 redistribute bgp
 default-information originate