hostname BGP
log file /var/log/quagga/bgpd.log
log stdout
password Quagga
enable password Quagga

router bgp 65002
 bgp router-id 172.31.255.252
 neighbor 172.31.255.253 remote-as 65001
 neighbor 172.31.255.253 activate
