hostname BGP
log file /var/log/quagga/bgpd.log
log stdout
password Quagga
enable password Quagga

access-list FilterInternal permit 10.0.0.0/8
access-list AllowExternal permit 172.16.0.0/12

route-map rm-filter-internal deny 10
 match ip address FilterInternal
route-map rm-filter-internal permit 20
 match ip address AllowExternal

router bgp 65001
 redistribute ospf route-map rm-filter-internal
 neighbor 172.31.255.252 remote-as 65002
 neighbor 172.31.255.252 activate
