events {}

http {
    upstream www_pool {
        server 172.16.123.130;
        server 172.16.123.131;
        server 172.16.123.132;
        server 172.16.123.133;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://www_pool;
        }
    }
}